jasypt:
  encryptor:
    password: efreight
dnspath: http://tom.t.efreight.cn
spring:
  redis:
#    host: 10.66.178.186
    host: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s
# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

  authorization:
    name: efreight OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://efreight-gateway:9999/auth/oauth/token

security:
  oauth2:
    client:
      ignore-urls:
        - /actuator/**
        - /operationPlan/printLetters/**
        - /operationPlan/printTag/**
        - /operationPlan/printTagMany/**
        - /coopBill/printBill/**
        - /aforder/printOrderLetter/**
        - /user/searchLoginNameAndOrgCode/**
        - /external/**
        - /services/AfAwbRouteWebService/**
        - /org/saveEfOrgUser/**
        - /org/sourceLoginOfEf/**
        - /tact/tactinfo/**
        - /ef/**
        - /identify/audit/**
    resource:
      loadBalanced: true
      token-info-uri: http://efreight-oauth/oauth/check_token
