security:
  oauth2:
    client:
      client-id: ENC(cuJHLOzZIJ/j/1VKvi8XIracgurUdeSt)
      client-secret: ENC(N8EuS95NdLArmDBNOJiWpy7iE5shlu3Q)
      scope: server

# 数据源
spring:
  datasource:
    url: jdbc:mysql://10.66.206.79:3306/tms?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: SaaS.OnlineProduct.Mysql-20200323
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    max-active: 100
    initial-size: 10
    min-idle: 10
    test-on-borrow: true
    max-wait: 60000
    web-stat-filter:
      exclusions: /static/*,/druid/*
      enabled: true
      url-pattern: /*
    stat-view-servlet:
      enabled: true
      login-username: zhanghw
      login-password: 123456
      url-pattern: /druid/*