package com.efreight.afbase.dao;



import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.efreight.afbase.entity.procedure.CssReportBusinessAnalysis;

public interface CssReportBusinessAnalysisMapper extends BaseMapper<CssReportBusinessAnalysis>{
	
	
	
	@Select({"<script>",
		"SELECT ",
		"<when test='bean.caliber==\"开航日\"'>",
		 	"DATE_FORMAT( a.expect_departure, ${bean.orderUnitValue} ) orderName,",
        "</when>",
        "<when test='bean.caliber==\"到港日\"'>",
        	"DATE_FORMAT( a.expect_arrival, ${bean.orderUnitValue} ) orderName,",
        "</when>",
			"<when test='bean.caliber==\"发车日\"'>",
			"DATE_FORMAT( a.expect_departure, ${bean.orderUnitValue} ) orderName,",
			"</when>",
			"<when test='bean.caliber==\"到达日\"'>",
			"DATE_FORMAT( a.expect_arrival, ${bean.orderUnitValue} ) orderName,",
			"</when>",
			"<when test='bean.caliber==\"用车日\"'>",
			"DATE_FORMAT( a.driving_time, ${bean.orderUnitValue} ) orderName,",
			"</when>",
			"<when test='bean.caliber==\"业务日\"'>",
			"DATE_FORMAT( a.business_date, ${bean.orderUnitValue} ) orderName,",
			"</when>",
        "<when test='bean.caliber==\"财务日\"'>",
	    	"DATE_FORMAT( c.financial_date, ${bean.orderUnitValue} ) orderName,",
	    "</when>",
		" COUNT(1) orderValue,",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		" sum(IFNULL(a.container_number,0)) containerNumber,",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
	    "</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			" sum(IFNULL(a.container_number,0)) containerNumber,",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
			"</when>",
	    "<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
	    "SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
	    "</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"SUM(IFNULL(a.plan_charge_weight/1000,0)) totalWeight,",
			"</when>",
		"IFNULL(SUM(c.incomeAmount)/10000,0) incomeAmount,",
		"IFNULL(SUM(c.incomeAmount)/10000,0)-IFNULL(SUM(c.costAmount)/10000,0) costAmount",

		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
			" FROM af_order a",
			"LEFT JOIN af_awb_number b ON a.awb_id=b.awb_id	",
        "</when>",
        "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
        	"FROM sc_order a",
        "</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"FROM tc_order a",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"FROM lc_order a",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"FROM io_order a",
			"</when>",
		
		"LEFT JOIN ",
		"(",
		"	 SELECT ",	
		"	 aa.order_id, ",
		"    CASE ",
		"	 WHEN income1.financial_date IS NOT NULL AND cost1.financial_date IS NOT NULL ",
		"    THEN",
		"    	IF(income1.financial_date <![CDATA[ < ]]> cost1.financial_date,income1.financial_date,cost1.financial_date) ",
		"    ELSE",
		" 		IF(income1.financial_date IS NOT NULL,income1.financial_date,cost1.financial_date)",
		"	 end AS financial_date ",
		"	 ,income.income_functional_amount incomeAmount ",
		"	  ,cost.cost_functional_amount costAmount ",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"	FROM af_order aa ",
		"	LEFT JOIN (" ,
		"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
		"      FROM af_income  M" ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"      GROUP BY M.order_id ", 
		"   ) income ON aa.order_id=income.order_id ",
		"	LEFT JOIN (" ,
		"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
		"       FROM af_income M" ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"       GROUP BY M.order_id ", 
		"   ) income1 ON aa.order_id=income1.order_id ",
		"	LEFT JOIN (",
		"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ", 
		"		 FROM af_cost M ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"		 GROUP BY M.order_id ",
		"	) cost ON aa.order_id=cost.order_id  ",
		"	LEFT JOIN (",
		"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ", 
		"		 FROM af_cost M ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"        WHERE M.financial_date IS NOT NULL ",
		"		 GROUP BY M.order_id ",
		"   ) cost1 ON aa.order_id=cost1.order_id  ",
	    "</when>",
	    "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
	    "	FROM sc_order aa ",
	    "	LEFT JOIN (" ,
		"  SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
		"  FROM sc_income M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"  GROUP BY M.order_id ", 
		" ) income ON aa.order_id=income.order_id ",
		"	LEFT JOIN (" ,
		"  SELECT M.order_id, MIN(M.financial_date) AS financial_date",
		"  FROM sc_income M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"  GROUP BY M.order_id ", 
		" ) income1 ON aa.order_id=income1.order_id ",
		"	LEFT JOIN ( " , 
		"  SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount  ", 
		"  FROM sc_cost M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"  GROUP BY M.order_id " ,
		" ) cost ON aa.order_id=cost.order_id  ",
		"	LEFT JOIN ( " , 
		"  SELECT M.order_id,MIN(M.financial_date) AS financial_date ", 
		"  FROM sc_cost M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"  GROUP BY M.order_id " ,
		" ) cost1 ON aa.order_id=cost1.order_id  ",
	    "</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"	FROM tc_order aa ",
			"	LEFT JOIN (" ,
			"  SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"  FROM tc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"  GROUP BY M.order_id ",
			" ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"  SELECT M.order_id, MIN(M.financial_date) AS financial_date",
			"  FROM tc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"  GROUP BY M.order_id ",
			" ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN ( " ,
			"  SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount  ",
			"  FROM tc_cost M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"  GROUP BY M.order_id " ,
			" ) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN ( " ,
			"  SELECT M.order_id,MIN(M.financial_date) AS financial_date ",
			"  FROM tc_cost M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"  GROUP BY M.order_id " ,
			" ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"	FROM lc_order aa ",
			"	LEFT JOIN (" ,
			"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"      FROM lc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"      GROUP BY M.order_id ",
			"   ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
			"       FROM lc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"       GROUP BY M.order_id ",
			"   ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ",
			"		 FROM lc_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"		 GROUP BY M.order_id ",
			"	) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ",
			"		 FROM lc_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"        WHERE M.financial_date IS NOT NULL ",
			"		 GROUP BY M.order_id ",
			"   ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"	FROM io_order aa ",
			"	LEFT JOIN (" ,
			"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"      FROM io_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"      GROUP BY M.order_id ",
			"   ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
			"       FROM io_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"       GROUP BY M.order_id ",
			"   ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ",
			"		 FROM io_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"		 GROUP BY M.order_id ",
			"	) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ",
			"		 FROM io_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"        WHERE M.financial_date IS NOT NULL ",
			"		 GROUP BY M.order_id ",
			"   ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
		"	WHERE 1=1 ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND aa.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND aa.org_id = #{bean.orgId} ",
		"</when>",
		"	GROUP BY aa.order_id",
		"	) c on a.order_id=c.order_id ",
		"WHERE  a.order_status!='强制关闭' ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND a.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND a.org_id = #{bean.orgId} ",
		"</when>",
		"<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
        " AND a.business_scope = #{bean.businessScope}",
        "</when>",
        "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"开航日\"'>",
        	" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
        "</when>",
        "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"开航日\"'>",
        	" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
        "</when>",
        "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到港日\"'>",
        	" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
        "</when>",
        "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到港日\"'>",
        	" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
        "</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
        "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"财务日\"'>",
    	" AND c.financial_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
	    "</when>",
	    "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"财务日\"'>",
	    	" AND c.financial_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
	    "</when>",
		"<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"财务锁账\"'>",
			" AND a.order_status = #{bean.orderStatus}",
        "</when>",
        "<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"未锁账\"'>",
		" AND a.order_status != '财务锁账'",
        "</when>",
        "<when test='bean.businessProduct!=null and bean.businessProduct!=\"\"'>",
        	" AND a.business_product = #{bean.businessProduct}",
        "</when>",
        "<when test='bean.awbFromType!=null and bean.awbFromType!=\"\"'>",
        	" AND b.awb_from_type = #{bean.awbFromType}",
        "</when>",
        "<when test='bean.containerMethod!=null and bean.containerMethod!=\"\"'>",
        	" AND a.container_method = #{bean.containerMethod}",
        "</when>",
        "<when test='bean.caliber==\"开航日\"'>",
    		"GROUP BY DATE_FORMAT( a.expect_departure, ${bean.orderUnitValue} )",
			"ORDER BY DATE_FORMAT( a.expect_departure, ${bean.orderUnitValue} ) ",
        "</when>",
        "<when test='bean.caliber==\"到港日\"'>",
    		"GROUP BY DATE_FORMAT( a.expect_arrival, ${bean.orderUnitValue} )",
			"ORDER BY DATE_FORMAT( a.expect_arrival, ${bean.orderUnitValue} ) ",
        "</when>",
			"<when test='bean.caliber==\"发车日\"'>",
			"GROUP BY DATE_FORMAT( a.expect_departure, ${bean.orderUnitValue} )",
			"ORDER BY DATE_FORMAT( a.expect_departure, ${bean.orderUnitValue} ) ",
			"</when>",
			"<when test='bean.caliber==\"到达日\"'>",
			"GROUP BY DATE_FORMAT( a.expect_arrival, ${bean.orderUnitValue} )",
			"ORDER BY DATE_FORMAT( a.expect_arrival, ${bean.orderUnitValue} ) ",
			"</when>",
			"<when test='bean.caliber==\"用车日\"'>",
			"GROUP BY DATE_FORMAT( a.driving_time, ${bean.orderUnitValue} )",
			"ORDER BY DATE_FORMAT( a.driving_time, ${bean.orderUnitValue} ) ",
			"</when>",
			"<when test='bean.caliber==\"业务日\"'>",
			"GROUP BY DATE_FORMAT( a.business_date, ${bean.orderUnitValue} )",
			"ORDER BY DATE_FORMAT( a.business_date, ${bean.orderUnitValue} ) ",
			"</when>",
        "<when test='bean.caliber==\"财务日\"'>",
			"GROUP BY DATE_FORMAT( c.financial_date, ${bean.orderUnitValue} )",
			"ORDER BY DATE_FORMAT( c.financial_date, ${bean.orderUnitValue} ) ",
		"</when>",
    "</script>"})
	List<Map<String, String>> getListPage(@Param("bean") CssReportBusinessAnalysis bean);
	@Select({"<script>",
		"SELECT ",
		"<when test='bean.caliber==\"开航日\"'>",
		"YEARWEEK(a.expect_departure,1) orderName,",
		"</when>",
			"<when test='bean.caliber==\"发车日\"'>",
			"YEARWEEK(a.expect_departure,1) orderName,",
			"</when>",
			"<when test='bean.caliber==\"到达日\"'>",
			"YEARWEEK(a.expect_arrival,1) orderName,",
			"</when>",
			"<when test='bean.caliber==\"用车日\"'>",
			"YEARWEEK(a.driving_time,1) orderName,",
			"</when>",
			"<when test='bean.caliber==\"业务日\"'>",
			"YEARWEEK(a.business_date,1) orderName,",
			"</when>",
		"<when test='bean.caliber==\"到港日\"'>",
		"YEARWEEK(a.expect_arrival,1) orderName,",
		"</when>",
		"<when test='bean.caliber==\"财务日\"'>",
		"YEARWEEK(c.financial_date,1)  orderName,",
		"</when>",
		" COUNT(1) orderValue,",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		" SUM(IFNULL(a.container_number,0)) containerNumber,",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			" SUM(IFNULL(a.container_number,0)) containerNumber,",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
			"</when>",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
		"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"SUM(IFNULL(a.plan_charge_weight/1000,0)) totalWeight,",
			"</when>",
		"IFNULL(SUM(c.incomeAmount)/10000,0) incomeAmount,",
		"IFNULL(SUM(c.incomeAmount)/10000,0)-IFNULL(SUM(c.costAmount)/10000,0) costAmount",

		
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		" FROM af_order a",
		"LEFT JOIN af_awb_number b ON a.awb_id=b.awb_id	",
		"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		"FROM sc_order a",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"FROM tc_order a",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"FROM lc_order a",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"FROM io_order a",
			"</when>",
		
		"LEFT JOIN ",
		"(",
		"	 SELECT ",	
		"	 aa.order_id, ",
		"    CASE ",
		"	 WHEN income1.financial_date IS NOT NULL AND cost1.financial_date IS NOT NULL ",
		"    THEN",
		"    	IF(income1.financial_date <![CDATA[ < ]]> cost1.financial_date,income1.financial_date,cost1.financial_date) ",
		"    ELSE",
		" 		IF(income1.financial_date IS NOT NULL,income1.financial_date,cost1.financial_date)",
		"	 end AS financial_date ",
		"	 ,income.income_functional_amount incomeAmount ",
		"	  ,cost.cost_functional_amount costAmount ",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"	FROM af_order aa ",
		"	LEFT JOIN (" ,
		"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
		"      FROM af_income  M" ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"      GROUP BY M.order_id ", 
		"   ) income ON aa.order_id=income.order_id ",
		"	LEFT JOIN (" ,
		"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
		"       FROM af_income M" ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"       GROUP BY M.order_id ", 
		"   ) income1 ON aa.order_id=income1.order_id ",
		"	LEFT JOIN (",
		"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ", 
		"		 FROM af_cost M ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"		 GROUP BY M.order_id ",
		"	) cost ON aa.order_id=cost.order_id  ",
		"	LEFT JOIN (",
		"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ", 
		"		 FROM af_cost M ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"        WHERE M.financial_date IS NOT NULL ",
		"		 GROUP BY M.order_id ",
		"   ) cost1 ON aa.order_id=cost1.order_id  ",
	    "</when>",
	    "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
	    "	FROM sc_order aa ",
	    "	LEFT JOIN (" ,
		"  SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
		"  FROM sc_income M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"  GROUP BY M.order_id ", 
		" ) income ON aa.order_id=income.order_id ",
		"	LEFT JOIN (" ,
		"  SELECT M.order_id, MIN(M.financial_date) AS financial_date",
		"  FROM sc_income M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"  GROUP BY M.order_id ", 
		" ) income1 ON aa.order_id=income1.order_id ",
		"	LEFT JOIN ( " , 
		"  SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount  ", 
		"  FROM sc_cost M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"  GROUP BY M.order_id " ,
		" ) cost ON aa.order_id=cost.order_id  ",
		"	LEFT JOIN ( " , 
		"  SELECT M.order_id,MIN(M.financial_date) AS financial_date ", 
		"  FROM sc_cost M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"  GROUP BY M.order_id " ,
		" ) cost1 ON aa.order_id=cost1.order_id  ",
	    "</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"	FROM tc_order aa ",
			"	LEFT JOIN (" ,
			"  SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"  FROM tc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"  GROUP BY M.order_id ",
			" ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"  SELECT M.order_id, MIN(M.financial_date) AS financial_date",
			"  FROM tc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"  GROUP BY M.order_id ",
			" ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN ( " ,
			"  SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount  ",
			"  FROM tc_cost M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"  GROUP BY M.order_id " ,
			" ) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN ( " ,
			"  SELECT M.order_id,MIN(M.financial_date) AS financial_date ",
			"  FROM tc_cost M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"  GROUP BY M.order_id " ,
			" ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"	FROM lc_order aa ",
			"	LEFT JOIN (" ,
			"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"      FROM lc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"      GROUP BY M.order_id ",
			"   ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
			"       FROM lc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"       GROUP BY M.order_id ",
			"   ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ",
			"		 FROM lc_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"		 GROUP BY M.order_id ",
			"	) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ",
			"		 FROM lc_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"        WHERE M.financial_date IS NOT NULL ",
			"		 GROUP BY M.order_id ",
			"   ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"	FROM io_order aa ",
			"	LEFT JOIN (" ,
			"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"      FROM io_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"      GROUP BY M.order_id ",
			"   ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
			"       FROM io_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"       GROUP BY M.order_id ",
			"   ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ",
			"		 FROM io_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"		 GROUP BY M.order_id ",
			"	) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ",
			"		 FROM io_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"        WHERE M.financial_date IS NOT NULL ",
			"		 GROUP BY M.order_id ",
			"   ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
		"	WHERE 1=1 ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND aa.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND aa.org_id = #{bean.orgId} ",
		"</when>",
		"	GROUP BY aa.order_id",
		"	) c on a.order_id=c.order_id ",
		"WHERE  a.order_status!='强制关闭' ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND a.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND a.org_id = #{bean.orgId} ",
		"</when>",
		"<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
		" AND a.business_scope = #{bean.businessScope}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"财务锁账\"'>",
		" AND a.order_status = #{bean.orderStatus}",
	    "</when>",
	    "<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"未锁账\"'>",
		" AND a.order_status != '财务锁账'",
	    "</when>",
		"<when test='bean.businessProduct!=null and bean.businessProduct!=\"\"'>",
		" AND a.business_product = #{bean.businessProduct}",
		"</when>",
		"<when test='bean.awbFromType!=null and bean.awbFromType!=\"\"'>",
		" AND b.awb_from_type = #{bean.awbFromType}",
		"</when>",
		"<when test='bean.containerMethod!=null and bean.containerMethod!=\"\"'>",
		" AND a.container_method = #{bean.containerMethod}",
		"</when>",
		"<when test='bean.caliber==\"开航日\"'>",
		"GROUP BY YEARWEEK(a.expect_departure,1) ",
		"ORDER BY YEARWEEK(a.expect_departure,1) ",
		"</when>",
		"<when test='bean.caliber==\"到港日\"'>",
		"GROUP BY YEARWEEK(a.expect_arrival,1) ",
		"ORDER BY YEARWEEK(a.expect_arrival,1) ",
		"</when>",
			"<when test='bean.caliber==\"发车日\"'>",
			"GROUP BY YEARWEEK(a.expect_departure,1) ",
			"ORDER BY YEARWEEK(a.expect_departure,1) ",
			"</when>",
			"<when test='bean.caliber==\"到达日\"'>",
			"GROUP BY YEARWEEK(a.expect_arrival,1) ",
			"ORDER BY YEARWEEK(a.expect_arrival,1) ",
			"</when>",
			"<when test='bean.caliber==\"用车日\"'>",
			"GROUP BY YEARWEEK(a.driving_time,1) ",
			"ORDER BY YEARWEEK(a.driving_time,1) ",
			"</when>",
			"<when test='bean.caliber==\"业务日\"'>",
			"GROUP BY YEARWEEK(a.business_date,1) ",
			"ORDER BY YEARWEEK(a.business_date,1) ",
			"</when>",
		"<when test='bean.caliber==\"财务日\"'>",
		"GROUP BY YEARWEEK(c.financial_date,1) ",
		"ORDER BY YEARWEEK(c.financial_date,1) ",
		"</when>",
	"</script>"})
	List<Map<String, String>> getListPage2(@Param("bean") CssReportBusinessAnalysis bean);
	
	@Select({"<script>",
		"select coopName,",
		"IFNULL(orderValue,0) orderValue,",
		"IFNULL(totalWeight,0) totalWeight,",
		"IFNULL(incomeAmount/10000,0) incomeAmount,",
		"IFNULL(costAmount/10000,0) costAmount,",
		"case when totalWeight2!=0 then FORMAT(IFNULL(costAmount/totalWeight2,0),2) else 0.00 end incomeAmount2,",
		"case when incomeAmount!=0 then FORMAT(IFNULL(costAmount/incomeAmount*100,0),2) else 0.00 end costAmount2",
		" from (",
		"SELECT ",
		" d.coop_name coopName,",
		" COUNT(1) orderValue,",
		"<when test='(bean.businessScope==\"SI\" or bean.businessScope==\"SE\") and bean.containerMethod!=\"整箱\"'>",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight2,",
		"</when>",
		"<when test='(bean.businessScope==\"SI\" or bean.businessScope==\"SE\") and bean.containerMethod==\"整箱\"'>",
		"sum(IFNULL(a.container_number,0)) totalWeight,",
		"sum(IFNULL(a.container_number,0)) totalWeight2,",
		"</when>",
			"<when test='(bean.businessScope==\"TE\" or bean.businessScope==\"TI\") and bean.containerMethod!=\"整箱\"'>",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight2,",
			"</when>",
			"<when test='(bean.businessScope==\"TE\" or bean.businessScope==\"TI\") and bean.containerMethod==\"整箱\"'>",
			"sum(IFNULL(a.container_number,0)) totalWeight,",
			"sum(IFNULL(a.container_number,0)) totalWeight2,",
			"</when>",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
		"SUM(IFNULL(a.confirm_charge_weight,a.plan_charge_weight)) totalWeight2,",
		"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
			"SUM(IFNULL(a.confirm_charge_weight,a.plan_charge_weight)) totalWeight2,",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"SUM(IFNULL(a.plan_charge_weight/1000,0)) totalWeight,",
			"SUM(IFNULL(a.plan_charge_weight,0)) totalWeight2,",
			"</when>",
		"IFNULL(SUM(c.incomeAmount),0) incomeAmount,",
		"IFNULL(SUM(c.incomeAmount),0)-IFNULL(SUM(c.costAmount),0) costAmount",
		
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		" FROM af_order a",
		"LEFT JOIN af_awb_number b ON a.awb_id=b.awb_id	",
		"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		"FROM sc_order a",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"FROM tc_order a",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"FROM lc_order a",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"FROM io_order a",
			"</when>",
		"LEFT JOIN prm_coop d ON a.coop_id=d.coop_id",
		"LEFT JOIN ",
		"(",
		"	 SELECT ",	
		"	 aa.order_id, ",
		"    CASE ",
		"	 WHEN income1.financial_date IS NOT NULL AND cost1.financial_date IS NOT NULL ",
		"    THEN",
		"    	IF(income1.financial_date <![CDATA[ < ]]> cost1.financial_date,income1.financial_date,cost1.financial_date) ",
		"    ELSE",
		" 		IF(income1.financial_date IS NOT NULL,income1.financial_date,cost1.financial_date)",
		"	 end AS financial_date ",
		"	 ,income.income_functional_amount incomeAmount ",
		"	  ,cost.cost_functional_amount costAmount ",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"	FROM af_order aa ",
		"	LEFT JOIN (" ,
		"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
		"      FROM af_income  M" ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"      GROUP BY M.order_id ", 
		"   ) income ON aa.order_id=income.order_id ",
		"	LEFT JOIN (" ,
		"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
		"       FROM af_income M" ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"       GROUP BY M.order_id ", 
		"   ) income1 ON aa.order_id=income1.order_id ",
		"	LEFT JOIN (",
		"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ", 
		"		 FROM af_cost M ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"		 GROUP BY M.order_id ",
		"	) cost ON aa.order_id=cost.order_id  ",
		"	LEFT JOIN (",
		"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ", 
		"		 FROM af_cost M ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"        WHERE M.financial_date IS NOT NULL ",
		"		 GROUP BY M.order_id ",
		"   ) cost1 ON aa.order_id=cost1.order_id  ",
	    "</when>",
	    "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
	    "	FROM sc_order aa ",
	    "	LEFT JOIN (" ,
		"  SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
		"  FROM sc_income M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"  GROUP BY M.order_id ", 
		" ) income ON aa.order_id=income.order_id ",
		"	LEFT JOIN (" ,
		"  SELECT M.order_id, MIN(M.financial_date) AS financial_date",
		"  FROM sc_income M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"  GROUP BY M.order_id ", 
		" ) income1 ON aa.order_id=income1.order_id ",
		"	LEFT JOIN ( " , 
		"  SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount  ", 
		"  FROM sc_cost M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"  GROUP BY M.order_id " ,
		" ) cost ON aa.order_id=cost.order_id  ",
		"	LEFT JOIN ( " , 
		"  SELECT M.order_id,MIN(M.financial_date) AS financial_date ", 
		"  FROM sc_cost M " ,
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
		"</when>",
		"       WHERE M.financial_date IS NOT NULL ",
		"  GROUP BY M.order_id " ,
		" ) cost1 ON aa.order_id=cost1.order_id  ",
	    "</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"	FROM tc_order aa ",
			"	LEFT JOIN (" ,
			"  SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"  FROM tc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"  GROUP BY M.order_id ",
			" ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"  SELECT M.order_id, MIN(M.financial_date) AS financial_date",
			"  FROM tc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"  GROUP BY M.order_id ",
			" ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN ( " ,
			"  SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount  ",
			"  FROM tc_cost M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"  GROUP BY M.order_id " ,
			" ) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN ( " ,
			"  SELECT M.order_id,MIN(M.financial_date) AS financial_date ",
			"  FROM tc_cost M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"  GROUP BY M.order_id " ,
			" ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"	FROM lc_order aa ",
			"	LEFT JOIN (" ,
			"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"      FROM lc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"      GROUP BY M.order_id ",
			"   ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
			"       FROM lc_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"       GROUP BY M.order_id ",
			"   ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ",
			"		 FROM lc_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"		 GROUP BY M.order_id ",
			"	) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ",
			"		 FROM lc_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"        WHERE M.financial_date IS NOT NULL ",
			"		 GROUP BY M.order_id ",
			"   ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"	FROM io_order aa ",
			"	LEFT JOIN (" ,
			"      SELECT M.order_id,SUM(M.income_functional_amount) AS income_functional_amount ",
			"      FROM io_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"      GROUP BY M.order_id ",
			"   ) income ON aa.order_id=income.order_id ",
			"	LEFT JOIN (" ,
			"       SELECT M.order_id,MIN(M.financial_date) AS financial_date",
			"       FROM io_income M " ,
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"       WHERE M.financial_date IS NOT NULL ",
			"       GROUP BY M.order_id ",
			"   ) income1 ON aa.order_id=income1.order_id ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id,SUM(M.cost_functional_amount) AS cost_functional_amount ",
			"		 FROM io_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"		 GROUP BY M.order_id ",
			"	) cost ON aa.order_id=cost.order_id  ",
			"	LEFT JOIN (",
			"		 SELECT M.order_id, MIN(M.financial_date) AS financial_date ",
			"		 FROM io_cost M ",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON M.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"        WHERE M.financial_date IS NOT NULL ",
			"		 GROUP BY M.order_id ",
			"   ) cost1 ON aa.order_id=cost1.order_id  ",
			"</when>",
		"	WHERE 1=1 ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND aa.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND aa.org_id = #{bean.orgId} ",
		"</when>",
		"	GROUP BY aa.order_id",
		"	) c on a.order_id=c.order_id ",
		"WHERE  a.order_status!='强制关闭' ",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND a.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND a.org_id = #{bean.orgId} ",
		"</when>",
		"<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
		" AND a.business_scope = #{bean.businessScope}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"财务锁账\"'>",
		" AND a.order_status = #{bean.orderStatus}",
	    "</when>",
	    "<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"未锁账\"'>",
		" AND a.order_status != '财务锁账'",
	    "</when>",
		"<when test='bean.businessProduct!=null and bean.businessProduct!=\"\"'>",
		" AND a.business_product = #{bean.businessProduct}",
		"</when>",
		"<when test='bean.awbFromType!=null and bean.awbFromType!=\"\"'>",
		" AND b.awb_from_type = #{bean.awbFromType}",
		"</when>",
		"<when test='bean.containerMethod!=null and bean.containerMethod!=\"\"'>",
		" AND a.container_method = #{bean.containerMethod}",
		"</when>",
		"GROUP BY  a.coop_id ",
		") cc",
		"ORDER BY  cc.costAmount DESC ",
	"</script>"})
	List<Map<String, String>> getList3(@Param("bean") CssReportBusinessAnalysis bean);
	@Select({"<script>",
		"select coopName,",
		"FORMAT(IFNULL(orderValue,0),0) orderValue,",
		"<when test='bean.containerMethod==\"整箱\"'>",
		" totalWeight,",
		"</when>",
		"<when test='bean.containerMethod!=\"整箱\"'>",
		"FORMAT(IFNULL(totalWeight,0),2) totalWeight,",
		"</when>",
		"FORMAT(IFNULL(costAmount/10000,0),2) costAmount,",
		"case when totalWeight2!=0 then FORMAT(IFNULL(costAmount/totalWeight2,0),2) else 0.00 end costAmount2",
		" from (",
		"SELECT ",
		" d.coop_name coopName,",
		" COUNT(1) orderValue,",
		"<when test='(bean.businessScope==\"SI\" or bean.businessScope==\"SE\") and bean.containerMethod!=\"整箱\"'>",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight2,",
		"</when>",
		"<when test='(bean.businessScope==\"SI\" or bean.businessScope==\"SE\") and bean.containerMethod==\"整箱\"'>",
		"sum(IFNULL(a.container_number,0)) totalWeight,",
		"sum(IFNULL(a.container_number,0)) totalWeight2,",
		"</when>",
			"<when test='(bean.businessScope==\"TE\" or bean.businessScope==\"TI\") and bean.containerMethod!=\"整箱\"'>",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight2,",
			"</when>",
			"<when test='(bean.businessScope==\"TE\" or bean.businessScope==\"TI\") and bean.containerMethod==\"整箱\"'>",
			"sum(IFNULL(a.container_number,0)) totalWeight,",
			"sum(IFNULL(a.container_number,0)) totalWeight2,",
			"</when>",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
		"SUM(IFNULL(a.confirm_charge_weight,a.plan_charge_weight)) totalWeight2,",
		"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
			"SUM(IFNULL(a.confirm_charge_weight,a.plan_charge_weight)) totalWeight2,",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"SUM(IFNULL(a.plan_charge_weight/1000,0)) totalWeight,",
			"SUM(IFNULL(a.plan_charge_weight,0)) totalWeight2,",
			"</when>",
		
		"IFNULL(SUM(c.costAmount),0) costAmount",

		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		" FROM af_order a",
		"LEFT JOIN af_awb_number b ON a.awb_id=b.awb_id	",
		"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		"FROM sc_order a",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"FROM tc_order a",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"FROM lc_order a",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"FROM io_order a",
			"</when>",
		"LEFT JOIN ",
		"(",
		"	 SELECT ",	
		"	 cost.customer_id, ",
		"	 cost.order_id, ",
		"	 MIN(cost.financial_date) AS financial_date ",
		"	  ,SUM(cost.cost_functional_amount) costAmount ",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"	FROM af_cost cost ",
		"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		"	FROM sc_cost cost ",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"	FROM tc_cost cost ",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"	FROM lc_cost cost ",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"	FROM io_cost cost ",
			"</when>",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON cost.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			"  WHERE cost.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
			"</when>",
			"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
			"  WHERE cost.org_id = #{bean.orgId} ",
			"</when>",
		"	GROUP BY cost.customer_id,cost.order_id",
		"	) c on a.order_id=c.order_id ",
		"LEFT JOIN prm_coop d ON c.customer_id=d.coop_id",
		"WHERE  a.order_status!='强制关闭' AND a.cost_status!='未录成本'",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND a.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND a.org_id = #{bean.orgId} ",
		"</when>",
		"<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
		" AND a.business_scope = #{bean.businessScope}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"财务锁账\"'>",
		" AND a.order_status = #{bean.orderStatus}",
	    "</when>",
	    "<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"未锁账\"'>",
		" AND a.order_status != '财务锁账'",
	    "</when>",
		"<when test='bean.businessProduct!=null and bean.businessProduct!=\"\"'>",
		" AND a.business_product = #{bean.businessProduct}",
		"</when>",
		"<when test='bean.awbFromType!=null and bean.awbFromType!=\"\"'>",
		" AND b.awb_from_type = #{bean.awbFromType}",
		"</when>",
		"<when test='bean.containerMethod!=null and bean.containerMethod!=\"\"'>",
		" AND a.container_method = #{bean.containerMethod}",
		"</when>",
		"GROUP BY  c.customer_id ",
		") cc",
		"ORDER BY  cc.costAmount DESC ",
	"</script>"})
	List<Map<String, String>> getList4(@Param("bean") CssReportBusinessAnalysis bean);
	@Select({"<script>",
		"select ",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		" coopName,",
		"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		"aa.port_name_en  coopName,",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"coopName,",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"aa.city_name_cn  coopName,",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"coopName,",
			"</when>",
		"FORMAT(IFNULL(orderValue,0),0) orderValue,",
		"<when test='bean.containerMethod==\"整箱\"'>",
		" totalWeight,",
		"</when>",
		"<when test='bean.containerMethod!=\"整箱\"'>",
		"FORMAT(IFNULL(totalWeight,0),2) totalWeight,",
		"</when>",
		
		"FORMAT(IFNULL(costAmount/10000,0),2) costAmount,",
		"case when totalWeight2!=0 then FORMAT(IFNULL(costAmount/totalWeight2,0),2) else 0.00 end costAmount2",
		" from (",
		"SELECT ",
		"<when test='bean.businessScope==\"SE\" or bean.businessScope==\"AE\"'>",
		"a.arrival_station  coopName,",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"a.arrival_station  coopName,",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"a.arrival_station  coopName,",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"a.arrival_station  coopName,",
			"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"AI\"'>",
		"a.departure_station  coopName,",
		"</when>",
		" COUNT(1) orderValue,",
		"<when test='(bean.businessScope==\"SI\" or bean.businessScope==\"SE\") and bean.containerMethod!=\"整箱\"'>",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
		"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight2,",
		"</when>",
		"<when test='(bean.businessScope==\"SI\" or bean.businessScope==\"SE\") and bean.containerMethod==\"整箱\"'>",
		"sum(IFNULL(a.container_number,0)) totalWeight,",
		"sum(IFNULL(a.container_number,0)) totalWeight2,",
		"</when>",
			"<when test='(bean.businessScope==\"TE\" or bean.businessScope==\"TI\") and bean.containerMethod!=\"整箱\"'>",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight,",
			"SUM(CASE WHEN container_method !='整箱' THEN IFNULL(a.plan_charge_weight,0) ELSE 0 END) totalWeight2,",
			"</when>",
			"<when test='(bean.businessScope==\"TE\" or bean.businessScope==\"TI\") and bean.containerMethod==\"整箱\"'>",
			"sum(IFNULL(a.container_number,0)) totalWeight,",
			"sum(IFNULL(a.container_number,0)) totalWeight2,",
			"</when>",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
		"SUM(IFNULL(a.confirm_charge_weight,a.plan_charge_weight)) totalWeight2,",
		"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"SUM(IFNULL(a.confirm_charge_weight/1000,a.plan_charge_weight/1000)) totalWeight,",
			"SUM(IFNULL(a.confirm_charge_weight,a.plan_charge_weight)) totalWeight2,",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"SUM(IFNULL(a.plan_charge_weight/1000,0)) totalWeight,",
			"SUM(IFNULL(a.plan_charge_weight,0)) totalWeight2,",
			"</when>",
		
		"IFNULL(SUM(c.costAmount),0) costAmount",
		
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		" FROM af_order a",
		"LEFT JOIN af_awb_number b ON a.awb_id=b.awb_id	",
		"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		"FROM sc_order a",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"FROM tc_order a",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"FROM lc_order a",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"FROM io_order a",
			"</when>",
		"LEFT JOIN ",
		"(",
		"	 SELECT ",	
		"	 cost.order_id, ",
		"	 MIN(cost.financial_date) AS financial_date ",
		"	  ,SUM(cost.cost_functional_amount) costAmount ",
		"<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
		"	FROM af_cost cost ",
		"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
		"	FROM sc_cost cost ",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"	FROM tc_cost cost ",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"	FROM lc_cost cost ",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"	FROM io_cost cost ",
			"</when>",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			" INNER JOIN prm_coop coop ON cost.customer_id = coop.coop_id and coop.is_internal = 0",
			"</when>",
			"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
			"  WHERE cost.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
			"</when>",
			"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
			"  WHERE cost.org_id = #{bean.orgId} ",
			"</when>",
		
		"	GROUP BY cost.order_id",
		"	) c on a.order_id=c.order_id ",

		"WHERE  a.order_status!='强制关闭'",
		"<when test='bean.otherOrg!=null and bean.otherOrg==-1'>",
		"  AND a.org_id IN (select org_id from hrs_org where group_id = #{bean.orgId}) ",
		"</when>",
		"<when test='(bean.otherOrg!=null and bean.otherOrg!=-1) or bean.otherOrg==null'>",
		"  AND a.org_id = #{bean.orgId} ",
		"</when>",
		"<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
		" AND a.business_scope = #{bean.businessScope}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"开航日\"'>",
		" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到港日\"'>",
		" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"发车日\"'>",
			" AND a.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"到达日\"'>",
			" AND a.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"用车日\"'>",
			" AND a.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
			"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
			"</when>",
			"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"业务日\"'>",
			" AND a.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
			"</when>",
		"<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
		"</when>",
		"<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.caliber==\"财务日\"'>",
		" AND c.financial_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
		"</when>",
		"<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"财务锁账\"'>",
		" AND a.order_status = #{bean.orderStatus}",
	    "</when>",
	    "<when test='bean.orderStatus!=null and bean.orderStatus!=\"\" and bean.orderStatus==\"未锁账\"'>",
		" AND a.order_status != '财务锁账'",
	    "</when>",
		"<when test='bean.businessProduct!=null and bean.businessProduct!=\"\"'>",
		" AND a.business_product = #{bean.businessProduct}",
		"</when>",
		"<when test='bean.awbFromType!=null and bean.awbFromType!=\"\"'>",
		" AND b.awb_from_type = #{bean.awbFromType}",
		"</when>",
		"<when test='bean.containerMethod!=null and bean.containerMethod!=\"\"'>",
		" AND a.container_method = #{bean.containerMethod}",
		"</when>",
		"<when test='bean.businessScope==\"SE\" or bean.businessScope==\"AE\"'>",
		"GROUP BY  a.arrival_station  ",
		"</when>",
			"<when test='bean.businessScope==\"TE\" or bean.businessScope==\"TI\"'>",
			"GROUP BY  a.arrival_station  ",
			"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"GROUP BY  a.arrival_station  ",
			"</when>",
			"<when test='bean.businessScope==\"IO\"'>",
			"GROUP BY  a.arrival_station  ",
			"</when>",
		"<when test='bean.businessScope==\"SI\" or bean.businessScope==\"AI\"'>",
		"GROUP BY  a.departure_station  ",
		"</when>",
		") cc",
		"<when test='bean.businessScope==\"SE\" or bean.businessScope==\"SI\"'>",
		"left join sc_port_maintenance aa on cc.coopName=aa.port_code",
		"</when>",
			"<when test='bean.businessScope==\"LC\"'>",
			"left join (SELECT city_code,max(city_name_cn) as city_name_cn FROM af_airport GROUP BY city_code) aa on cc.coopName=aa.city_code",
			"</when>",

		"ORDER BY  cc.totalWeight DESC ",
	"</script>"})
	List<Map<String, String>> getList5(@Param("bean") CssReportBusinessAnalysis bean);
}
