package com.efreight.afbase.dao;

import com.efreight.afbase.entity.AfIncome;
import com.efreight.afbase.entity.DebitNote;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.mapping.StatementType;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

/**
 * <p>
 * 清单 Mapper 接口
 * </p>
 *
 * @author xiaobo
 * @since 2019-11-07
 */
public interface DebitNoteMapper extends BaseMapper<DebitNote> {

    @Select("select tom_F_format_money(#{amount})")
    String calltomFFormatMoney(@Param("amount") BigDecimal amount);

    @Select({"<script>",
            "    SELECT a.* ,d.statement_num,c.invoice_remark invoiceRemark2,c.invoice_num invoiceNum2,c.invoice_title invoiceTitle2,c.invoice_date invoiceDate2,",
            "b.Order_Code,b.Customer_Number,",
            "<when test='bean.businessScope==\"AI\" '>",
            "CASE WHEN b.awb_number IS NOT NULL AND b.awb_number !='' AND b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN CONCAT(b.awb_number,'_', b.hawb_number)",
            "WHEN b.awb_number IS NOT NULL AND b.awb_number !='' THEN b.awb_number ",
            "WHEN b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN b.hawb_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate,b.expect_flight flightNo",
            "</when>",
            "<when test='bean.businessScope==\"AE\" '>",
            "b.Awb_Number,b.Expect_Departure FlightDate,b.expect_flight flightNo",
            "</when>",
            "<when test='bean.businessScope==\"SI\"'>",
            "CASE WHEN b.mbl_number IS NOT NULL AND b.mbl_number!='' AND b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN CONCAT(b.mbl_number,'_', b.hbl_number)",
            "WHEN b.mbl_number IS NOT NULL AND b.mbl_number !='' THEN b.mbl_number ",
            "WHEN b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN b.hbl_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate,b.ship_voyage_number flightNo",
            "</when>",

            "<when test='bean.businessScope==\"SE\"'>",
            "b.mbl_number awbNumber,b.Expect_Departure FlightDate,b.ship_voyage_number flightNo",
            "</when>",
            "<when test='bean.businessScope==\"TE\"'>",
            "b.rwb_number awbNumber,b.product_type,b.Expect_Departure FlightDate,'' AS flightNo",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "b.customer_number awbNumber,b.shipping_method,b.driving_time FlightDate,'' AS flightNo",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "b.customer_number awbNumber,b.business_method,b.business_date FlightDate,'' AS flightNo",
            "</when>",

            "FROM css_debit_note a",
            "LEFT JOIN css_statement d ON a.statement_id=d.statement_id",
            "<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
            "LEFT JOIN af_order b ON a.order_id=b.order_id",
            "INNER JOIN ",
            "(SELECT debit_note_id FROM af_income ",
            "WHERE org_id=#{bean.orgId}",
            "<when test='bean.serviceIdStr!=null and bean.serviceIdStr!=\"\"'>",
            "and service_id in (${bean.serviceIdStr})",
            "</when>",
            "GROUP BY debit_note_id",
            " ) c ",
            " ON a.debit_note_id=c.debit_note_id",
            "</when>",

            "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
            "LEFT JOIN sc_order b ON a.order_id=b.order_id",
            "INNER JOIN ",
            "(SELECT debit_note_id FROM sc_income ",
            "WHERE org_id=#{bean.orgId}",
            "<when test='bean.serviceIdStr!=null and bean.serviceIdStr!=\"\"'>",
            "and service_id in (${bean.serviceIdStr})",
            "</when>",
            "GROUP BY debit_note_id",
            " ) c ",
            " ON a.debit_note_id=c.debit_note_id",
            "</when>",

            "<when test='bean.businessScope==\"TI\" or bean.businessScope==\"TE\"'>",
            "LEFT JOIN tc_order b ON a.order_id=b.order_id",
            "INNER JOIN ",
            "(SELECT debit_note_id FROM tc_income ",
            "WHERE org_id=#{bean.orgId}",
            "<when test='bean.serviceIdStr!=null and bean.serviceIdStr!=\"\"'>",
            "and service_id in (${bean.serviceIdStr})",
            "</when>",
            "GROUP BY debit_note_id",
            " ) c ",
            " ON a.debit_note_id=c.debit_note_id",
            "</when>",

            "<when test='bean.businessScope==\"LC\"'>",
            "LEFT JOIN lc_order b ON a.order_id=b.order_id",
            "INNER JOIN ",
            "(SELECT debit_note_id FROM lc_income ",
            "WHERE org_id=#{bean.orgId}",
            "<when test='bean.serviceIdStr!=null and bean.serviceIdStr!=\"\"'>",
            "and service_id in (${bean.serviceIdStr})",
            "</when>",
            "GROUP BY debit_note_id",
            " ) c ",
            " ON a.debit_note_id=c.debit_note_id",
            "</when>",

            "<when test='bean.businessScope==\"IO\"'>",
            "LEFT JOIN io_order b ON a.order_id=b.order_id",
            "INNER JOIN ",
            "(SELECT debit_note_id FROM io_income ",
            "WHERE org_id=#{bean.orgId}",
            "<when test='bean.serviceIdStr!=null and bean.serviceIdStr!=\"\"'>",
            "and service_id in (${bean.serviceIdStr})",
            "</when>",
            "GROUP BY debit_note_id",
            " ) c ",
            " ON a.debit_note_id=c.debit_note_id",
            "</when>",

            "LEFT JOIN css_statement c ON a.statement_id=c.statement_id",
            " WHERE 1=1 and a.org_id=#{bean.orgId} ",

            "<when test='bean.billStatus!=null and bean.billStatus!=\"\"'>",
            " and ( 1=2 ",
            "</when>",
            "<when test='bean.billStatus1==\"已制账单\"'>",
            " or ( a.writeoff_complete IS NULL  AND a.statement_id IS NULL)",
            "</when>",
            "<when test='bean.billStatus2==\"已制清单\"'>",
            " or a.statement_id IS NOT NULL",
            "</when>",
            "<when test='bean.billStatus3==\"核销完毕\"'>",
            " or a.writeoff_complete=1",
            "</when>",
            "<when test='bean.billStatus4==\"部分核销\"'>",
            " or a.writeoff_complete=0",
            "</when>",
            "<when test='bean.billStatus!=null and bean.billStatus!=\"\"'>",
            ")",
            "</when>",

            "<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
            " AND a.business_scope = #{bean.businessScope}",
            "</when>",
            "<when test='bean.debitNoteNum!=null and bean.debitNoteNum!=\"\"'>",
            " AND a.debit_note_num like  \"%\"#{bean.debitNoteNum}\"%\"",
            "</when>",
            "<when test='bean.customerName!=null and bean.customerName!=\"\"'>",
            " AND a.customer_name like  \"%\"#{bean.customerName}\"%\"",
            "</when>",
            "<when test='bean.creatorName!=null and bean.creatorName!=\"\"'>",
            " AND a.creator_name like  \"%\"#{bean.creatorName}\"%\"",
            "</when>",
            "<when test='bean.debitNoteDateStart!=null and bean.debitNoteDateStart!=\"\"'>",
            " AND a.debit_note_date  <![CDATA[ >= ]]> #{bean.debitNoteDateStart}",
            "</when>",
            "<when test='bean.debitNoteDateEnd!=null and bean.debitNoteDateEnd!=\"\"'>",
            " AND a.debit_note_date <![CDATA[ <= ]]> #{bean.debitNoteDateEnd}",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"AE\"'>",
            " AND b.awb_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"SE\"'>",
            " AND b.mbl_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"TE\"'>",
            " AND b.rwb_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.customer_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.customer_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"AI\"'>",
            " AND (b.awb_number like  \"%\"#{bean.awbNumber}\"%\" or b.hawb_number like  \"%\"#{bean.awbNumber}\"%\")",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"SI\" '>",
            " AND (b.mbl_number like  \"%\"#{bean.awbNumber}\"%\" or b.hbl_number like  \"%\"#{bean.awbNumber}\"%\")",
            "</when>",
            "<when test='bean.orderCode!=null and bean.orderCode!=\"\"'>",
            " AND b.order_code like  \"%\"#{bean.orderCode}\"%\"",
            "</when>",
            "<when test='bean.customerNumber!=null and bean.customerNumber!=\"\"'>",
            " AND b.customer_number like  \"%\"#{bean.customerNumber}\"%\"",
            "</when>",
            "<when test='bean.statementNum!=null and bean.statementNum!=\"\"'>",
            " AND d.statement_num like  \"%\"#{bean.statementNum}\"%\"",
            "</when>",
            "<when test='bean.flightNo!=null and bean.flightNo!=\"\" and (bean.businessScope==\"AE\" or bean.businessScope==\"AI\")'>",
            " AND upper(b.expect_flight) like  \"%\"#{bean.flightNo}\"%\"",
            "</when>",
            "<when test='bean.flightNo!=null and bean.flightNo!=\"\" and (bean.businessScope==\"SE\" or bean.businessScope==\"SI\")'>",
            " AND upper(b.ship_voyage_number) like  \"%\"#{bean.flightNo}\"%\"",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and (bean.businessScope==\"AE\" or bean.businessScope==\"SE\" or bean.businessScope==\"TE\")'>",
            " AND b.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and (bean.businessScope==\"AE\" or bean.businessScope==\"SE\" or bean.businessScope==\"TE\")'>",
            " AND b.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and (bean.businessScope==\"AI\" or bean.businessScope==\"SI\")'>",
            " AND b.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and (bean.businessScope==\"AI\" or bean.businessScope==\"SI\")'>",
            " AND b.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.invoiceNum!=null and bean.invoiceNum!=\"\"'>",
            " AND ((a.invoice_num like \"%\"#{bean.invoiceNum}\"%\" and a.statement_id IS NULL) or (c.invoice_num like \"%\"#{bean.invoiceNum}\"%\" and a.statement_id IS NOT NULL))",
            "</when>",
            "<when test='bean.invoiceTitle!=null and bean.invoiceTitle!=\"\"'>",
            " AND ((a.invoice_title like \"%\"#{bean.invoiceTitle}\"%\" and a.statement_id IS NULL) or (c.invoice_title like \"%\"#{bean.invoiceTitle}\"%\" and a.statement_id IS NOT NULL))",
            "</when>",
            "<when test='bean.invoiceDateStart!=null and bean.invoiceDateStart!=\"\"'>",
            " AND ((a.invoice_date  <![CDATA[ >= ]]> #{bean.invoiceDateStart} and a.statement_id IS NULL) or (c.invoice_date  <![CDATA[ >= ]]> #{bean.invoiceDateStart} and a.statement_id IS NOT NULL))",
            "</when>",
            "<when test='bean.invoiceDateEnd!=null and bean.invoiceDateEnd!=\"\"'>",
            " AND ((a.invoice_date  <![CDATA[ <= ]]> #{bean.invoiceDateEnd} and a.statement_id IS NULL) or (c.invoice_date  <![CDATA[ <= ]]> #{bean.invoiceDateEnd} and a.statement_id IS NOT NULL))",
            "</when>",
//        "order by a.customer_id , a.income_writeoff_id DESC",
            "order by a.customer_id , a.debit_note_id DESC",
            "</script>"})
    IPage<DebitNote> getPage(Page page, @Param("bean") DebitNote bean);

    @Select({"<script>",
            "    SELECT a.* ,",
            "b.Order_Code,b.Customer_Number,",
            "<when test='bean.businessScope==\"AI\" '>",
            "CASE WHEN b.awb_number IS NOT NULL AND b.awb_number !='' AND b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN CONCAT(b.awb_number,'_', b.hawb_number)",
            "WHEN b.awb_number IS NOT NULL AND b.awb_number !='' THEN b.awb_number ",
            "WHEN b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN b.hawb_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"AE\" '>",
            "b.Awb_Number,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SI\"'>",
            "CASE WHEN b.mbl_number IS NOT NULL AND b.mbl_number!='' AND b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN CONCAT(b.mbl_number,'_', b.hbl_number)",
            "WHEN b.mbl_number IS NOT NULL AND b.mbl_number !='' THEN b.mbl_number ",
            "WHEN b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN b.hbl_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SE\"'>",
            "b.mbl_number awbNumber,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"TE\"'>",
            "b.rwb_number awbNumber,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "b.customer_number awbNumber,b.driving_time FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "b.customer_number awbNumber,b.business_date FlightDate",
            "</when>",
            "FROM css_debit_note a",
            "<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
            "LEFT JOIN af_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
            "LEFT JOIN sc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"TI\" or bean.businessScope==\"TE\"'>",
            "LEFT JOIN tc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "LEFT JOIN lc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "LEFT JOIN io_order b ON a.order_id=b.order_id",
            "</when>",
            " WHERE 1=1 and a.org_id=#{bean.orgId} and statement_id = #{bean.statementId}",
            "<when test='bean.amountTaxRate!=null and bean.amountTaxRate!=\"\"'>",
            " AND a.amount_tax_rate = #{bean.amountTaxRate}",
            "</when>",
            "<when test='bean.debitNoteId!=null and bean.debitNoteId!=\"\"'>",
            " AND a.debitNoteId = #{bean.debitNoteId}",
            "</when>",
            "<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
            " AND a.business_scope = #{bean.businessScope}",
            "</when>",
            "<when test='bean.debitNoteNum!=null and bean.debitNoteNum!=\"\"'>",
            " AND a.debit_note_num like  \"%\"#{bean.debitNoteNum}\"%\"",
            "</when>",
            "<when test='bean.customerName!=null and bean.customerName!=\"\"'>",
            " AND a.customer_name = #{bean.customerName}",
            "</when>",
            "<when test='bean.debitNoteDateStart!=null and bean.debitNoteDateStart!=\"\"'>",
            " AND a.debit_note_date  <![CDATA[ >= ]]> #{bean.debitNoteDateStart}",
            "</when>",
            "<when test='bean.debitNoteDateEnd!=null and bean.debitNoteDateEnd!=\"\"'>",
            " AND a.debit_note_date <![CDATA[ <= ]]> #{bean.debitNoteDateEnd}",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"AE\"'>",
            " AND b.awb_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"SE\"'>",
            " AND b.mbl_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"TE\"'>",
            " AND b.rwb_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.customer_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.customer_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"AI\"'>",
            " AND (b.awb_number like  \"%\"#{bean.awbNumber}\"%\" or b.hawb_number like  \"%\"#{bean.awbNumber}\"%\")",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"SI\" '>",
            " AND (b.mbl_number like  \"%\"#{bean.awbNumber}\"%\" or b.hbl_number like  \"%\"#{bean.awbNumber}\"%\")",
            "</when>",
            "<when test='bean.orderCode!=null and bean.orderCode!=\"\"'>",
            " AND b.order_code like  \"%\"#{bean.orderCode}\"%\"",
            "</when>",
            "<when test='bean.customerNumber!=null and bean.customerNumber!=\"\"'>",
            " AND b.customer_number like  \"%\"#{bean.customerNumber}\"%\"",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and (bean.businessScope==\"AE\" or bean.businessScope==\"SE\" or bean.businessScope==\"TE\")'>",
            " AND b.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and (bean.businessScope==\"AE\" or bean.businessScope==\"SE\" or bean.businessScope==\"TE\")'>",
            " AND b.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and (bean.businessScope==\"AI\" or bean.businessScope==\"SI\")'>",
            " AND b.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and (bean.businessScope==\"AI\" or bean.businessScope==\"SI\")'>",
            " AND b.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "</script>"})
    List<DebitNote> select2(@Param("bean") DebitNote bean);

    @Select({"<script>",
            "    SELECT a.* ,",
            "b.Order_Code,b.Customer_Number,",
            "<when test='bean.businessScope==\"AI\" '>",
            "CASE WHEN b.awb_number IS NOT NULL AND b.awb_number !='' AND b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN CONCAT(b.awb_number,'_', b.hawb_number)",
            "WHEN b.awb_number IS NOT NULL AND b.awb_number !='' THEN b.awb_number ",
            "WHEN b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN b.hawb_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"AE\" '>",
            "b.Awb_Number,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SI\"'>",
            "CASE WHEN b.mbl_number IS NOT NULL AND b.mbl_number!='' AND b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN CONCAT(b.mbl_number,'_', b.hbl_number)",
            "WHEN b.mbl_number IS NOT NULL AND b.mbl_number !='' THEN b.mbl_number ",
            "WHEN b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN b.hbl_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SE\"'>",
            "b.mbl_number awbNumber,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"TE\"'>",
            "b.rwb_number awbNumber,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "b.customer_number awbNumber,b.driving_time FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "b.customer_number awbNumber,b.business_date FlightDate",
            "</when>",
            "FROM css_debit_note a",

            "<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
            "LEFT JOIN af_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
            "LEFT JOIN sc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"TI\" or bean.businessScope==\"TE\"'>",
            "LEFT JOIN tc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "LEFT JOIN lc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "LEFT JOIN io_order b ON a.order_id=b.order_id",
            "</when>",

            " WHERE 1=1 and a.org_id=#{bean.orgId} and a.statement_id IS NULL and a.functional_amount_writeoff IS NULL ",
            "<when test='bean.amountTaxRate!=null and bean.amountTaxRate!=\"\"'>",
            " AND a.amount_tax_rate = #{bean.amountTaxRate}",
            "</when>",
            "<when test='bean.debitNoteId!=null and bean.debitNoteId!=\"\"'>",
            " AND a.debitNoteId = #{bean.debitNoteId}",
            "</when>",
            "<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
            " AND a.business_scope = #{bean.businessScope}",
            "</when>",
            "<when test='bean.debitNoteNum!=null and bean.debitNoteNum!=\"\"'>",
            " AND a.debit_note_num like  \"%\"#{bean.debitNoteNum}\"%\"",
            "</when>",
            "<when test='bean.customerName!=null and bean.customerName!=\"\"'>",
            " AND a.customer_name = #{bean.customerName}",
            "</when>",
            "<when test='bean.debitNoteDateStart!=null and bean.debitNoteDateStart!=\"\"'>",
            " AND a.debit_note_date  <![CDATA[ >= ]]> #{bean.debitNoteDateStart}",
            "</when>",
            "<when test='bean.debitNoteDateEnd!=null and bean.debitNoteDateEnd!=\"\"'>",
            " AND a.debit_note_date <![CDATA[ <= ]]> #{bean.debitNoteDateEnd}",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"AE\"'>",
            " AND b.awb_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"SE\"'>",
            " AND b.mbl_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"TE\"'>",
            " AND b.rwb_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.customer_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.customer_number like  \"%\"#{bean.awbNumber}\"%\"",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"AI\"'>",
            " AND (b.awb_number like  \"%\"#{bean.awbNumber}\"%\" or b.hawb_number like  \"%\"#{bean.awbNumber}\"%\")",
            "</when>",
            "<when test='bean.awbNumber!=null and bean.awbNumber!=\"\" and bean.businessScope==\"SI\" '>",
            " AND (b.mbl_number like  \"%\"#{bean.awbNumber}\"%\" or b.hbl_number like  \"%\"#{bean.awbNumber}\"%\")",
            "</when>",
            "<when test='bean.orderCode!=null and bean.orderCode!=\"\"'>",
            " AND b.order_code like  \"%\"#{bean.orderCode}\"%\"",
            "</when>",
            "<when test='bean.customerNumber!=null and bean.customerNumber!=\"\"'>",
            " AND b.customer_number like  \"%\"#{bean.customerNumber}\"%\"",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and (bean.businessScope==\"AE\" or bean.businessScope==\"SE\" or bean.businessScope==\"TE\")'>",
            " AND b.expect_departure  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and (bean.businessScope==\"AE\" or bean.businessScope==\"SE\" or bean.businessScope==\"TE\")'>",
            " AND b.expect_departure <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and (bean.businessScope==\"AI\" or bean.businessScope==\"SI\")'>",
            " AND b.expect_arrival  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and (bean.businessScope==\"AI\" or bean.businessScope==\"SI\")'>",
            " AND b.expect_arrival <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.driving_time  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.businessScope==\"LC\"'>",
            " AND b.driving_time <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.flightDateStart!=null and bean.flightDateStart!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.business_date  <![CDATA[ >= ]]> #{bean.flightDateStart}",
            "</when>",
            "<when test='bean.flightDateEnd!=null and bean.flightDateEnd!=\"\" and bean.businessScope==\"IO\"'>",
            " AND b.business_date <![CDATA[ <= ]]> #{bean.flightDateEnd}",
            "</when>",
            "<when test='bean.debitNoteIds!=null and bean.debitNoteIds!=\"\"'>",
            "AND debit_note_id NOT IN",
            "<foreach collection='debitNoteIds' item='debitNoteId' open='(' separator=',' close=')'>",
            "#{debitNoteId}",
            "</foreach>",
            "</when>",
            "</script>"})
    List<DebitNote> select22(@Param("bean") DebitNote bean, @Param("debitNoteIds") String[] debitNoteIds);

    @Select({"<script>",
            "    SELECT a.* ,",
            "c.statement_num, ",
            "b.Order_Code,b.Customer_Number,",
            "<when test='bean.businessScope==\"AI\" '>",
            "CASE WHEN b.awb_number IS NOT NULL AND b.awb_number !='' AND b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN CONCAT(b.awb_number,'_', b.hawb_number)",
            "WHEN b.awb_number IS NOT NULL AND b.awb_number !='' THEN b.awb_number ",
            "WHEN b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN b.hawb_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"AE\" '>",
            "b.Awb_Number,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SI\"'>",
            "CASE WHEN b.mbl_number IS NOT NULL AND b.mbl_number!='' AND b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN CONCAT(b.mbl_number,'_', b.hbl_number)",
            "WHEN b.mbl_number IS NOT NULL AND b.mbl_number !='' THEN b.mbl_number ",
            "WHEN b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN b.hbl_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SE\"'>",
            "b.mbl_number awbNumber,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"TE\"'>",
            "b.rwb_number awbNumber,b.expect_departure flightDate",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "b.customer_number awbNumber,b.driving_time flightDate",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "b.customer_number awbNumber,b.business_date flightDate",
            "</when>",
            "FROM css_debit_note a",
            "<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
            "LEFT JOIN af_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
            "LEFT JOIN sc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"TI\" or bean.businessScope==\"TE\"'>",
            "LEFT JOIN tc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "LEFT JOIN lc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "LEFT JOIN io_order b ON a.order_id=b.order_id",
            "</when>",
            "LEFT JOIN css_statement c ON a.statement_id=c.statement_id",
            " WHERE 1=1 and a.org_id=#{bean.orgId} ",

            "<when test='bean.orderCode!=null and bean.orderCode!=\"\"'>",
            " AND b.order_code like  \"%\"#{bean.orderCode}\"%\"",
            "</when>",
            "<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
            " AND a.business_scope=#{bean.businessScope}",
            "</when>",

            "</script>"})
    List<DebitNote> selectOperation(@Param("bean") DebitNote bean);

    @Select({"<script>",
            "    SELECT a.* ,",
            "c.statement_num ,",
            "b.Order_Code,b.Customer_Number,",
            "<when test='bean.businessScope==\"AI\" '>",
            "CASE WHEN b.awb_number IS NOT NULL AND b.awb_number !='' AND b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN CONCAT(b.awb_number,'_', b.hawb_number)",
            "WHEN b.awb_number IS NOT NULL AND b.awb_number !='' THEN b.awb_number ",
            "WHEN b.hawb_number IS NOT NULL AND b.hawb_number !='' THEN b.hawb_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"AE\" '>",
            "b.Awb_Number,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SI\"'>",
            "CASE WHEN b.mbl_number IS NOT NULL AND b.mbl_number!='' AND b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN CONCAT(b.mbl_number,'_', b.hbl_number)",
            "WHEN b.mbl_number IS NOT NULL AND b.mbl_number !='' THEN b.mbl_number ",
            "WHEN b.hbl_number IS NOT NULL AND b.hbl_number !='' THEN b.hbl_number",
            "ELSE '' END awbNumber",
            ",b.expect_arrival FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"SE\"'>",
            "b.mbl_number awbNumber,b.Expect_Departure FlightDate",
            "</when>",
            "<when test='bean.businessScope==\"TE\" '>",
            "b.rwb_number ",
            "</when>",
            "<when test='bean.businessScope==\"LC\" '>",
            "b.order_code awbNumber ",
            "</when>",
            "<when test='bean.businessScope==\"IO\" '>",
            "b.order_code awbNumber ",
            "</when>",
            "FROM css_debit_note a",
            "<when test='bean.businessScope==\"AI\" or bean.businessScope==\"AE\"'>",
            "LEFT JOIN af_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"SI\" or bean.businessScope==\"SE\"'>",
            "LEFT JOIN sc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"TI\" or bean.businessScope==\"TE\"'>",
            "LEFT JOIN tc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"LC\"'>",
            "LEFT JOIN lc_order b ON a.order_id=b.order_id",
            "</when>",
            "<when test='bean.businessScope==\"IO\"'>",
            "LEFT JOIN io_order b ON a.order_id=b.order_id",
            "</when>",
            "LEFT JOIN css_statement c ON a.statement_id=c.statement_id",
            " WHERE 1=1 and a.org_id=#{bean.orgId} ",

            "<when test='bean.businessScope!=null and bean.businessScope!=\"\"'>",
            " AND a.business_scope=#{bean.businessScope}",
            "</when>",
            "<when test='bean.debitNoteId!=null'>",
            " AND a.debit_note_id=#{bean.debitNoteId}",
            "</when>",
            "<when test='bean.orderCode!=null and bean.orderCode!=\"\"'>",
            " AND b.order_code like  \"%\"#{bean.orderCode}\"%\"",
            " order by a.debit_note_id DESC",
            "</when>",

            "</script>"})
    List<DebitNote> selectOperation2(@Param("bean") DebitNote bean);

    @Select({"<script>",
            " SELECT a.*,b.debit_note_num FROM af_income a  ",
            " LEFT JOIN css_debit_note b ON a.debit_note_id=b.debit_note_id",
            "	where a.org_id = #{org_id} and a.income_amount_writeoff IS NOT NULL and a.debit_note_id in (${debit_note_id}) \n",
            "</script>"})
    List<AfIncome> queryWriteoff(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id);

    @Select({"<script>",
            " SELECT a.* FROM css_debit_note a  ",
            "	where a.org_id = #{org_id} and a.writeoff_complete IS NOT NULL and a.debit_note_id in (${debit_note_id}) \n",
            "</script>"})
    List<DebitNote> queryWriteoffDebit(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id);

    @Select({"<script>",
            " SELECT a.*,b.debit_note_num FROM sc_income a  ",
            " LEFT JOIN css_debit_note b ON a.debit_note_id=b.debit_note_id",
            "	where a.org_id = #{org_id} and a.income_amount_writeoff IS NOT NULL and a.debit_note_id in (${debit_note_id}) \n",
            "</script>"})
    List<AfIncome> queryWriteoffSE(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id);

    @Delete("delete from css_debit_note where org_id=#{org_id} and statement_id IS NULL and invoice_id IS NULL and debit_note_id in (${debit_note_id})")
    void doDeleteBill(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id);

    @Delete("delete from css_debit_note_currency where org_id=#{org_id} and debit_note_id in (${debit_note_id})")
    void doDeleteBillCurrency(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id);

    @Update("update af_income set"
            + " debit_note_id = NULL "
            + ",row_uuid=#{row_uuid} "
            + " where org_id=#{org_id} and debit_note_id in (${debit_note_id})")
    void doUpdateIncome(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id, @Param("row_uuid") String row_uuid);

    @Update("update sc_income set"
            + " debit_note_id = NULL "
            + ",row_uuid=#{row_uuid} "
            + " where org_id=#{org_id} and debit_note_id in (${debit_note_id})")
    void doUpdateIncomeSE(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id, @Param("row_uuid") String row_uuid);

    @Update("update tc_income set"
            + " debit_note_id = NULL "
            + ",row_uuid=#{row_uuid} "
            + " where org_id=#{org_id} and debit_note_id in (${debit_note_id})")
    void doUpdateIncomeTC(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id, @Param("row_uuid") String row_uuid);

    @Update("update lc_income set"
            + " debit_note_id = NULL "
            + ",row_uuid=#{row_uuid} "
            + " where org_id=#{org_id} and debit_note_id in (${debit_note_id})")
    void doUpdateIncomeLC(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id, @Param("row_uuid") String row_uuid);

    @Update("update io_income set"
            + " debit_note_id = NULL "
            + ",row_uuid=#{row_uuid} "
            + " where org_id=#{org_id} and debit_note_id in (${debit_note_id})")
    void doUpdateIncomeIO(@Param("org_id") Integer org_id, @Param("debit_note_id") String debit_note_id, @Param("row_uuid") String row_uuid);


    @Select({"<script>",
            "    SELECT a.debit_note_id ,a.statement_id,a.invoice_id,a.writeoff_complete,a.debit_note_num,a.functional_amount,a.functional_amount_writeoff",
            "FROM css_debit_note a",
            " WHERE a.org_id=#{bean.orgId}",
            "<when test='bean.debitNoteIds!=null and bean.debitNoteIds!=\"\"'>",
            "AND a.debit_note_id  IN",
            "<foreach collection='debitNoteIds' item='debitNoteId' open='(' separator=',' close=')'>",
            "#{debitNoteId}",
            "</foreach>",
            "</when>",
            "</script>"})
    List<DebitNote> selectCheckDebit(@Param("bean") DebitNote bean, @Param("debitNoteIds") String[] debitNoteIds);


    @Update("update css_debit_note set"
            + " statement_id = NULL "
            + " where org_id=#{org_id} and debit_note_num=#{debitNoteNum}")
    void deleteDebitNote(@Param("org_id") Integer org_id, @Param("debitNoteNum") String debitNoteNum);

    @Update("update css_debit_note set"
            + " statement_id = #{statementId} "
            + " where org_id=#{org_id} and debit_note_id=#{debitNoteId}")
    void updateDebitNote(@Param("org_id") Integer org_id, @Param("debitNoteId") Integer debitNoteId, @Param("statementId") Integer statementId);

    @Options(statementType = StatementType.CALLABLE)
    @ResultMap({"print1", "print2"})
    @Select({"<script>",
            "CALL css_P_debit_note_print(#{org_id},#{businessScope},#{debit_note_list},#{debit_note_language},#{userId},#{templateFilePath})\n",
            "</script>"})
    List<List<Map<String, String>>> printManyNew(@Param("org_id") Integer org_id, @Param("businessScope") String businessScope, @Param("debit_note_list") String debit_note_list, @Param("debit_note_language") String debit_note_language, @Param("userId") Integer userId, @Param("templateFilePath") String templateFilePath);


}
