package com.efreight.afbase.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.efreight.afbase.entity.TactPublic;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TactPublicMapper extends BaseMapper<TactPublic> {

    @Select({"<script>",
            "SELECT " ,
            "A.publish_price_id publishPriceId, " ,
            "A.org_id orgId," ,
            "A.product_name productName," ,
            "A.carrier_code carrierCode," ,
            "A.departure_station departureStation," ,
            "A.arrival_station arrivalStation," ,
            "A.transit_station transitStation," ,
            "A.begin_date beginDate," ,
            "A.end_date AS endDate," ,
            "A.goods_type AS goodsType," ,
            "A.density_class AS densityClass," ,
            "A.tact_m tactM," ,
            "A.tact_n tactN," ,
            "A.tact_45 tact45," ,
            "A.tact_100 tact100," ,
            "A.tact_300 tact300," ,
            "A.tact_500 tact500," ,
            "A.tact_700 tact700," ,
            "A.tact_1000 tact1000," ,
            "A.tact_2000 tact2000," ,
            "A.tact_3000 tact3000," ,
            "A.tact_5000 tact5000," ,
            "A.tact_remark tactRemark," ,
            "SUBSTRING_INDEX(IF(A.editor_id IS NULL,A.creator_name,A.editor_name), ' ',  1) AS operator," ,
            "DATE_FORMAT(IF(A.editor_id IS NULL,A.create_time,A.edit_time), '%Y-%m-%d %T') AS operatTime" ,
            "FROM af_tact_publish_price A" ,
            "   WHERE 1=1",
            " AND A.org_id=#{bean.orgId}",
            "<when test='bean.carrierCode!=null and bean.carrierCode!=\"\"'>",
            " AND upper(A.carrier_code) LIKE CONCAT('%',upper(#{bean.carrierCode}),'%')",
            "</when>",
            "<when test='bean.departureStation!=null and bean.departureStation!=\"\"'>",
            " AND upper(A.departure_station) LIKE CONCAT('%',upper(#{bean.departureStation}),'%')",
            "</when>",
            "<when test='bean.arrivalStation!=null and bean.arrivalStation!=\"\"'>",
            " AND upper(A.arrival_station) LIKE CONCAT('%',upper(#{bean.arrivalStation}),'%')",
            "</when>",
            "<when test='bean.productName!=null and bean.productName!=\"\"'>",
            " AND A.product_name LIKE CONCAT('%',#{bean.productName},'%')",
            "</when>",
            "<when test='bean.transitStation!=null and bean.transitStation!=\"\"'>",
            " AND upper(A.transit_station) LIKE CONCAT('%',upper(#{bean.transitStation}),'%')",
            "</when>",
            "<when test='bean.goodsType!=null and bean.goodsType!=\"\"'>",
            " AND A.goods_type LIKE CONCAT('%',#{bean.goodsType},'%')",
            "</when>",
            "<when test='bean.densityClass!=null and bean.densityClass!=\"\"'>",
            " AND A.density_class LIKE CONCAT('%',#{bean.densityClass},'%')",
            "</when>",
            "<when test='bean.flightDate!=null and bean.flightDate!=\"\"'>",
            " AND A.begin_date &lt;= #{bean.flightDate}",
            "</when>",
            "<when test='bean.flightDate!=null and bean.flightDate!=\"\"'>",
            " AND A.end_date &gt;= #{bean.flightDate}",
            "</when>",
            "ORDER BY A.product_name ASC , A.carrier_code ASC,A.departure_station,A.arrival_station,A.begin_date,A.end_date DESC",
            "</script>"})
    IPage<TactPublic> getList(Page page, @Param("bean") TactPublic bean);
    @Select({"<script>",
        "SELECT " ,
        "A.publish_price_id publishPriceId, " ,
        "A.org_id orgId," ,
        "A.carrier_code carrierCode," ,
        "A.product_name productName," ,
        "A.departure_station departureStation," ,
        "A.arrival_station arrivalStation," ,
        "A.transit_station transitStation," ,
        "DATE_FORMAT(A.begin_date, '%Y-%m-%d') beginDateStr," ,
        "DATE_FORMAT(A.end_date, '%Y-%m-%d') AS endDateStr," ,
        "A.goods_type AS goodsType," ,
        "A.density_class AS densityClass," ,
        "A.tact_m tactM," ,
        "A.tact_n tactN," ,
        "A.tact_45 tact45," ,
        "A.tact_100 tact100," ,
        "A.tact_300 tact300," ,
        "A.tact_500 tact500," ,
        "A.tact_700 tact700," ,
        "A.tact_1000 tact1000," ,
        "A.tact_2000 tact2000," ,
        "A.tact_3000 tact3000," ,
        "A.tact_5000 tact5000," ,
        "A.tact_remark tactRemark," ,
        "SUBSTRING_INDEX(IF(A.editor_id IS NULL,A.creator_name,A.editor_name), ' ',  1) AS operator," ,
        "DATE_FORMAT(IF(A.editor_id IS NULL,A.create_time,A.edit_time), '%Y-%m-%d %T') AS operatTime" ,
        "FROM af_tact_publish_price A" ,
        "   WHERE 1=1",
        " AND A.org_id=#{bean.orgId}",
        "<when test='bean.carrierCode!=null and bean.carrierCode!=\"\"'>",
        " AND upper(A.carrier_code) LIKE CONCAT('%',upper(#{bean.carrierCode}),'%')",
        "</when>",
        "<when test='bean.departureStation!=null and bean.departureStation!=\"\"'>",
        " AND upper(A.departure_station) LIKE CONCAT('%',upper(#{bean.departureStation}),'%')",
        "</when>",
        "<when test='bean.arrivalStation!=null and bean.arrivalStation!=\"\"'>",
        " AND upper(A.arrival_station) LIKE CONCAT('%',upper(#{bean.arrivalStation}),'%')",
        "</when>",
        "<when test='bean.productName!=null and bean.productName!=\"\"'>",
        " AND A.product_name LIKE CONCAT('%',#{bean.productName},'%')",
        "</when>",
        "<when test='bean.transitStation!=null and bean.transitStation!=\"\"'>",
        " AND upper(A.transit_station) LIKE CONCAT('%',upper(#{bean.transitStation}),'%')",
        "</when>",
        "<when test='bean.goodsType!=null and bean.goodsType!=\"\"'>",
        " AND A.goods_type LIKE CONCAT('%',#{bean.goodsType},'%')",
        "</when>",
        "<when test='bean.densityClass!=null and bean.densityClass!=\"\"'>",
        " AND A.density_class LIKE CONCAT('%',#{bean.densityClass},'%')",
        "</when>",
        "<when test='bean.flightDate!=null and bean.flightDate!=\"\"'>",
        " AND A.begin_date &lt;= #{bean.flightDate}",
        "</when>",
        "<when test='bean.flightDate!=null and bean.flightDate!=\"\"'>",
        " AND A.end_date &gt;= #{bean.flightDate}",
        "</when>",
        "ORDER BY A.product_name ASC , A.carrier_code ASC,A.departure_station,A.arrival_station,A.begin_date,A.end_date DESC",
        "</script>"})
    List<TactPublic> queryListForExcel(@Param("bean") TactPublic bean);
}
